version: "3"

services:
  web:
    container_name: node_app
    restart: "always"
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none